'In python datatypes are considered as classes and every variable of its datatype is an object of that class of datatype'
'there is a function called type() where u can find the type of datatype'
'int, float, string, boolean are basic data types of python and manymore are there'
'0b or 0B :binary number,  0o or 0O : octal number, 0x or 0X : hexadecimal number'

var_1 = 123
var_2 = 10.1
var_3 = 0o123  # octal number
var_4 = 0x123  # hexa
print(var_1+10)  # addition for variable
print(var_1+var_2)  # addition of 2 numbers float and int
print(type(var_2))  # to find the datatype of variable
print(var_3)  # value of octal number
print(var_4)  # value of hexa num
print()
name = "sanjana kanavi"  # string
print(type(name))
print(name[3])  # can print specific character
print()
n_1 = "sanjana"
n_2 = "kartik"
print(n_2+n_1)  # concatination of string
# if we want to make single and double quote as string,use \ before quotes ,and can multiply how many times we want
print(4*"sanju\'s \\n \"katy\"")
var = True  # boolean
print(type(var))
print()
j = 1
i = 2
result = j < i  # checking conditions
print(result)
# India is a country in South Asia.